<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Auth Key' => '',
  'Check your email for further instructions.' => '',
  'Create Time' => '',
  'Date Of Birth' => '',
  'Email' => '',
  'Email Canonical' => '',
  'Email Confirmed' => '',
  'Facebook Data' => '',
  'Facebook Name' => '',
  'Facebook Uid' => '',
  'First Name' => '',
  'Follow the link below to reset your password:' => '',
  'Forgot Password?' => '',
  'Full Name' => '',
  'Gender' => '',
  'Gplus Data' => '',
  'Gplus Name' => '',
  'Gplus Uid' => '',
  'Hello {name},' => '',
  'ID' => '',
  'Incorrect username or password.' => '',
  'Last Name' => '',
  'Last visit time' => '',
  'Login' => '',
  'Login here' => '',
  'New password was saved.' => '',
  'Nick Name' => '',
  'Password' => '',
  'Password Hash' => '',
  'Password Reset Token' => '',
  'Password reset for {name}' => '',
  'Patronimic' => '',
  'Please choose your new password:' => '',
  'Please fill out your email. A link to reset password will be sent there.' => '',
  'Please sign in' => '',
  'Remember me' => '',
  'Remembered your password?' => '',
  'Request password reset' => '',
  'Reset password' => '',
  'Save' => '',
  'Send' => '',
  'Short Name' => '',
  'Status' => '',
  'There is no user with such email.' => '',
  'There was an error sending email.' => '',
  'This email address has already been taken.' => '',
  'Twitter Data' => '',
  'Twitter Name' => '',
  'Twitter Uid' => '',
  'Update Time' => '',
  'User with this email does not exist.' => '',
  'User with this username or email does not exist.' => '',
  'Username' => '',
  'Username Canonical' => '',
  'Verification code' => '',
  'Vk Data' => '',
  'Vk Name' => '',
  'Vk Uid' => '',
  'Wrong password reset token.' => '',
);
