<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Auth Key' => '',
  'Avatar' => '',
  'Backend authorization route' => '',
  'Check your email for further instructions.' => 'Проверьте свою почту для получения дальнейших инструкций.',
  'Create Time' => 'Дата создания',
  'Date Of Birth' => 'Дата рождения',
  'Email' => 'Email',
  'Email Canonical' => 'Канонический Email',
  'Email Confirmed' => 'Email подтвержден',
  'Facebook Data' => '',
  'Facebook Name' => '',
  'Facebook Uid' => '',
  'First Name' => 'Имя',
  'Follow the link below to reset your password:' => 'Пройдите по ссылке ниже, чтобы сбросить свой пароль:',
  'Forgot Password?' => 'Забыли пароль?',
  'Full Name' => 'Полное имя',
  'Gender' => 'Пол',
  'Gplus Data' => '',
  'Gplus Name' => '',
  'Gplus Uid' => '',
  'Hello {name},' => 'Здравствуйте, {name}',
  'ID' => '',
  'Incorrect username or password.' => 'Неверное сочетание логина и пароля.',
  'Last Name' => 'Фамилия',
  'Last visit time' => 'Время последнего посещения',
  'Login' => 'Войти',
  'Login here' => 'Войдите здесь',
  'New password was saved.' => 'Новый пароль сохранен.',
  'Nick Name' => 'Прозвище',
  'Password' => 'Пароль',
  'Password Hash' => '',
  'Password Reset Token' => '',
  'Password reset for {name}' => 'Сброс пароля для {name}',
  'Patronimic' => 'Отчество',
  'Please choose your new password:' => 'Введите новый пароль:',
  'Please fill out your email. A link to reset password will be sent there.' => 'Введите свой email. Ссылка для сброса пароля будет отправлена на него.',
  'Please sign in' => 'Войдите',
  'Provides authorization and password reset (with captcha) for backend application.' => '',
  'Remember me' => 'Запомнить',
  'Remembered your password?' => 'Вспомнили свой пароль?',
  'Request password reset' => 'Запрос сброса пароля',
  'Reset password' => 'Сбросить пароль',
  'Save' => 'Сохранить',
  'Send' => 'Отправить',
  'Short Name' => 'Краткое имя',
  'Status' => 'Статус',
  'There is no user with such email.' => 'Пользователь с таким адресом не найден.',
  'There was an error sending email.' => 'Произошла ошибка при посылке письма.',
  'This email address has already been taken.' => 'Этот адрес уже занят.',
  'Twitter Data' => '',
  'Twitter Name' => '',
  'Twitter Uid' => '',
  'Update Time' => 'Последнее обновление',
  'User with this email does not exist.' => '',
  'User with this username or email does not exist.' => 'Пользователь не найден.',
  'Username' => 'Логин',
  'Username Canonical' => 'Канонический логин',
  'Verification code' => 'Код проверки',
  'Vk Data' => '',
  'Vk Name' => '',
  'Vk Uid' => '',
  'Wrong password reset token.' => 'Неверный код сброса пароля.',

  '_module_description_' => 'Управление авторизацией, пользователями и их правами.',
  '_module_name_' => 'Пользователи',
);
